import "server-only";
import type { AnalyticsReport } from "./analytics-report-types";

// Verified baseline exported from the native platform dashboards and
// Google/Vercel tooling through 21 August 2026. The admin analytics service
// hydrates every supported field with live website, Search Console, connected
// social-platform and PageSpeed data. These values remain the safe fallback
// for unavailable APIs and for fields the platforms do not expose.
export const analyticsReport: AnalyticsReport = {
  preparedDate: "2026-08-21",
  executiveSummary: {
    preparedDate: "2026-08-21",
    kpis: [
      { label: "Website visitors · 30d", value: "294" },
      { label: "Page views · 30d", value: "1,836" },
      { label: "Google clicks", value: "30" },
      { label: "Google CTR", value: "36.6%" },
      { label: "Indexed pages", value: "17" },
      { label: "Mobile SEO score", value: "100" },
      { label: "Social exposures*", value: "17,217" },
      { label: "Facebook referrals", value: "49" },
      { label: "Site action events", value: "26" },
      { label: "Accessibility score", value: "97" },
    ],
    whatTheNumbersSay: [
      {
        area: "Website",
        evidence: "294 visitors generated 1,836 page views; 46% bounce rate.",
        meaning: "The early audience explores deeply (6.24 pages per visitor).",
        decision: "Protect the fast site experience and make calls to action measurable.",
      },
      {
        area: "Google Search",
        evidence: "22 clicks from 59 impressions; 37.3% CTR; average position 7.6.",
        meaning: "Very small sample, but strong relevance when OPR appears.",
        decision: "Grow impressions with recipe-led content and authoritative backlinks.",
      },
      {
        area: "Social discovery",
        evidence: "Instagram: 72.6% of views from non-followers. TikTok: 89.8% of recent traffic from For You.",
        meaning: "Short-form content is reaching beyond existing audiences.",
        decision: "Use stronger profile and end-card calls to action to convert discovery into site visits.",
      },
      {
        area: "Social traffic",
        evidence: "Facebook hostnames supplied 49 website visitors; Meta reports 15 Facebook link clicks.",
        meaning: "Facebook is the clearest social-to-site pathway today.",
        decision: "Keep direct recipe links in Facebook posts and apply source tracking everywhere.",
      },
      {
        area: "Technical SEO",
        evidence: "Sitemap succeeds; HTTPS and breadcrumbs are healthy; Lighthouse SEO 100.",
        meaning: "The technical foundation is strong.",
        decision: "Focus effort on authority, recipe discovery and video watch pages—not a redesign.",
      },
      {
        area: "Measurement",
        evidence: "Privacy-safe source, UTM campaign, site-action and conversion totals are now collected first-party.",
        meaning: "OPR can compare which links and campaigns turn discovery into participation without storing personal identifiers.",
        decision: "Use a stable source and campaign code on every social link, then review complete calendar-month totals.",
      },
    ],
    topPriorities: [
      { priority: "P1", action: "Increase Google visibility through richer verified recipe coverage and stronger contextual internal links.", whyNow: "OPR earns clicks when it appears, but broader non-brand recipe discovery remains the constraint.", successMeasure: "Complete-month Search Console reports show growth in non-brand recipe impressions, clicks and indexed recipe pages.", owner: "Content + site · monthly" },
      { priority: "P1", action: "Keep one clear primary action on every important landing page.", whyNow: "First-party source, campaign, action and conversion totals can now show which journeys turn exploration into participation.", successMeasure: "Each priority page has one named action and its complete-month conversion trend is reviewed.", owner: "Site + content · this month" },
      { priority: "P1", action: "Earn links from contributors, local press, food-history groups and relevant partners.", whyNow: "Only 13 external links are reported—and all are from the sister .com domain.", successMeasure: "10+ new relevant referring domains, each linking to a useful canonical page.", owner: "PR/content · weekly" },
      { priority: "P1", action: "Validate the community/1 redirect in Search Console.", whyNow: "The duplicate is permanently redirected, excluded from the sitemap and consolidated into Sudesh’s canonical recipe page.", successMeasure: "Google reports the duplicate as redirected and retains the canonical recipe.", owner: "Site · after deployment" },
      { priority: "P1", action: "Monitor dedicated film watch pages and the video sitemap in Search Console.", whyNow: "Every OPR film now has an indexable watch page, VideoObject data and a transcript.", successMeasure: "The priority film library becomes eligible for video search features.", owner: "Site/content · monthly" },
      { priority: "P1", action: "Remove/repost the TikTok caption containing accidental desktop interface text.", whyNow: "The caption is publicly untidy and weakens trust.", successMeasure: "Correct caption live; post checked on mobile and desktop.", owner: "Social · today" },
      { priority: "P2", action: "Improve YouTube titles and thumbnails; test one promise-led creative pattern.", whyNow: "4,000 impressions produced a 1.3% click-through rate.", successMeasure: "CTR moves towards a 3–5% working target without reducing retention.", owner: "Video · fortnightly" },
      { priority: "P2", action: "Turn search interest in bhindi and jollof into richer recipe-page coverage.", whyNow: "These are the clearest visible non-brand query themes.", successMeasure: "More recipe-page impressions and first clicks for non-brand searches.", owner: "Content · 2 articles/month" },
      { priority: "P2", action: "Review live PageSpeed and Vercel Speed Insights each month; fix any contrast and caption-track warnings.", whyNow: "Performance collection is live, so regressions can now be identified and acted on.", successMeasure: "Core Web Vitals and Lighthouse scores remain healthy; accessibility checks pass.", owner: "Site · monthly" },
    ],
    footnote: "*Social exposures add platform-reported views/impressions and are not deduplicated people. Native platform definitions and date windows differ; use this as an activity indicator, not total audience reach.",
  },

  website: {
    period: "Vercel Web Analytics · 30 days: 18 Jul–17 Aug 2026 · 7 days: 10–17 Aug 2026",
    core: [
      { metric: "Visitors", last30Days: 294, last7Days: 117, change7d: -0.13 },
      { metric: "Page views", last30Days: 1836, last7Days: 749, change7d: -0.16 },
      { metric: "Bounce rate", last30Days: 0.46, last7Days: 0.42, change7d: -0.07 },
      { metric: "Pages per visitor", last30Days: 6.24, last7Days: 6.4, change7d: null },
    ],
    topPages: [
      { path: "/", visitors: 196, role: "Homepage", seoNote: "Dominant landing page and 17 of 22 organic clicks." },
      { path: "/family-cookbook", visitors: 95, role: "Living Cookbook hub", seoNote: "Second-largest audience and 3 organic clicks." },
      { path: "/founder", visitors: 62, role: "Brand story", seoNote: "One organic click; strong early exploration." },
      { path: "/films", visitors: 57, role: "Film collection", seoNote: "One organic click; priority for dedicated watch pages." },
      { path: "/share", visitors: 43, role: "Recipe submission", seoNote: "12 search impressions but no clicks yet." },
      { path: "/our-story", visitors: 39, role: "Legacy URL", seoNote: "Old name still present in historical traffic/search data; retain 301." },
      { path: "/founding-table", visitors: 35, role: "Legacy URL", seoNote: "Old name still present in search data; retain 301 to Join Our Table." },
    ],
    topReferrers: [
      { host: "google.com", visitors: 35, channel: "Google", observation: "Largest single referrer host.", action: "Expand non-brand recipe discovery." },
      { host: "facebook.com", visitors: 32, channel: "Facebook", observation: "Main Facebook hostname.", action: "Keep direct recipe links." },
      { host: "m.facebook.com", visitors: 10, channel: "Facebook", observation: "Mobile Facebook traffic.", action: "Use mobile-first landing pages." },
      { host: "l.facebook.com", visitors: 7, channel: "Facebook", observation: "Facebook link shim.", action: "Use campaign/source tracking." },
      { host: "com.linkedin.android", visitors: 2, channel: "LinkedIn", observation: "Small early referral source.", action: "Use founder/mission stories." },
      { host: "uk.pinterest.com", visitors: 2, channel: "Pinterest", observation: "Early discovery traffic.", action: "Create vertical recipe pins." },
      { host: "vercel.com", visitors: 2, channel: "Technical", observation: "Likely preview/deployment traffic.", action: "Exclude from marketing decisions." },
    ],
    audienceCountry: [
      { country: "United Kingdom", share: 0.51, visitors: 150 },
      { country: "United States", share: 0.21, visitors: 62 },
      { country: "Greece", share: 0.11, visitors: 32 },
      { country: "Brazil", share: 0.05, visitors: 15 },
      { country: "India", share: 0.04, visitors: 12 },
      { country: "Other", share: 0.08, visitors: 24 },
    ],
    audienceDevice: [
      { device: "Mobile", share: 0.63 },
      { device: "Desktop", share: 0.36 },
      { device: "Tablet", share: 0.01 },
    ],
    audienceOS: [
      { os: "iOS", share: 0.49, visitors: 144 },
      { os: "Mac", share: 0.21, visitors: 62 },
      { os: "Android", share: 0.15, visitors: 44 },
      { os: "Windows", share: 0.11, visitors: 32 },
      { os: "Linux", share: 0.03, visitors: 9 },
    ],
    note: "Action-event rates divide events by visitors; they are not unique-user conversion rates and a person may complete more than one action. Vercel Hobby does not expose UTM reports or custom events.",
    fetchedAt: null,
  },

  googleSearch: {
    period: "Google Search Console · Data available 1–18 Aug 2026",
    kpis: [
      { metric: "Clicks", value: 30, definition: "Visits from Google Search", read: "Small but genuine organic demand." },
      { metric: "Impressions", value: 82, definition: "Times an OPR result appeared", read: "The main growth constraint is visibility." },
      { metric: "CTR", value: 0.366, definition: "Clicks ÷ impressions", read: "High, but based on a small sample." },
      { metric: "Average position", value: 7.6, definition: "Mean highest position", read: "Page-one average; query mix is limited." },
      { metric: "Indexed pages", value: 17, definition: "URLs eligible to appear", read: "77.3% of known URLs." },
      { metric: "Not indexed", value: 5, definition: "Known URLs not indexed", read: "Continue reviewing redirects and discovered URLs." },
    ],
    daily: [
      { date: "01 Aug", clicks: 0, impressions: 0, ctr: 0 },
      { date: "02 Aug", clicks: 3, impressions: 5, ctr: 0.6 },
      { date: "03 Aug", clicks: 1, impressions: 1, ctr: 1 },
      { date: "04 Aug", clicks: 1, impressions: 1, ctr: 1 },
      { date: "05 Aug", clicks: 0, impressions: 2, ctr: 0 },
      { date: "06 Aug", clicks: 3, impressions: 7, ctr: 0.43 },
      { date: "07 Aug", clicks: 2, impressions: 6, ctr: 0.33 },
      { date: "08 Aug", clicks: 1, impressions: 4, ctr: 0.25 },
      { date: "09 Aug", clicks: 0, impressions: 1, ctr: 0 },
      { date: "10 Aug", clicks: 1, impressions: 1, ctr: 1 },
      { date: "11 Aug", clicks: 4, impressions: 10, ctr: 0.4 },
      { date: "12 Aug", clicks: 2, impressions: 7, ctr: 0.29 },
      { date: "13 Aug", clicks: 0, impressions: 5, ctr: 0 },
      { date: "14 Aug", clicks: 2, impressions: 5, ctr: 0.4 },
      { date: "15 Aug", clicks: 2, impressions: 4, ctr: 0.5 },
      { date: "16–18 Aug", clicks: 8, impressions: 23, ctr: 0.35 },
    ],
    queries: [
      { query: "bhindi recipe", clicks: 0, impressions: 6 },
      { query: "3 cheese truffle charity bread", clicks: 0, impressions: 2 },
      { query: "bhindi ki recipe", clicks: 0, impressions: 2 },
      { query: "how to cook bhindi", clicks: 0, impressions: 1 },
      { query: "letter from our founder", clicks: 0, impressions: 1 },
      { query: "sam the cooking guy shepherd's pie", clicks: 0, impressions: 1 },
      { query: "Long-form jollof search (privacy-trimmed)", clicks: 0, impressions: 1 },
      { query: "Second long-form jollof search", clicks: 0, impressions: 1 },
    ],
    pages: [
      { page: "/", clicks: 17, impressions: 37 },
      { page: "/family-cookbook", clicks: 3, impressions: 19 },
      { page: "/films", clicks: 1, impressions: 12 },
      { page: "/founder", clicks: 1, impressions: 3 },
      { page: "http://otherpeoplesrecipes.co.uk/", clicks: 1, impressions: 2 },
      { page: "/share", clicks: 0, impressions: 12 },
      { page: "/our-story", clicks: 0, impressions: 11 },
      { page: "/family-cookbook/sudeshs-bhindi", clicks: 0, impressions: 8 },
      { page: "/family-cookbook/adas-jollof-rice", clicks: 0, impressions: 4 },
      { page: "/family-cookbook/krishna-anands-baingan-ka-bharta", clicks: 0, impressions: 4 },
      { page: "/family-cookbook/barbaras-beef-casserole", clicks: 0, impressions: 3 },
      { page: "/family-cookbook/nana-serbs-sunday-rice-pudding", clicks: 0, impressions: 2 },
      { page: "/family-cookbook/daves-butter-chicken", clicks: 0, impressions: 2 },
      { page: "/family-cookbook/sams-shepherds-pie", clicks: 0, impressions: 2 },
      { page: "/family-cookbook/phils-and-serbs-three-cheese-souffle", clicks: 0, impressions: 2 },
      { page: "/founding-table", clicks: 0, impressions: 1 },
    ],
    countries: [
      { country: "United Kingdom", clicks: 17, impressions: 27 },
      { country: "Greece", clicks: 3, impressions: 13 },
      { country: "Ireland", clicks: 1, impressions: 1 },
      { country: "Portugal", clicks: 1, impressions: 1 },
      { country: "India", clicks: 0, impressions: 7 },
      { country: "United States", clicks: 0, impressions: 4 },
      { country: "Canada", clicks: 0, impressions: 2 },
      { country: "Italy", clicks: 0, impressions: 1 },
      { country: "Saudi Arabia", clicks: 0, impressions: 1 },
      { country: "Pakistan", clicks: 0, impressions: 1 },
      { country: "Thailand", clicks: 0, impressions: 1 },
    ],
    devices: [
      { device: "Mobile", clicks: 17, impressions: 35 },
      { device: "Desktop", clicks: 5, impressions: 24 },
      { device: "Recipe Gallery", clicks: 0, impressions: 6 },
      { device: "Recipe rich result", clicks: 0, impressions: 2 },
    ],
    note: "Google withholds or anonymises many query rows for privacy, so visible queries do not reconcile to the 30 total clicks. The 16–18 Aug daily row is an aggregate derived from the change in the verified totals; page, country and device tables remain the latest export available from the detailed report.",
  },

  seoTechnical: {
    asOf: "2026-08-21",
    indexing: [
      { measure: "Indexed URLs", value: 17, status: "Healthy base", interpretation: "17 of 22 known URLs are indexed.", action: "Monitor as the site grows.", lastUpdate: "21 Aug" },
      { measure: "Not indexed", value: 5, status: "Review", interpretation: "Five known URLs are not indexed.", action: "Review redirects and genuinely missing pages.", lastUpdate: "21 Aug" },
      { measure: "Sitemap discovered pages", value: 17, status: "Success", interpretation: "sitemap.xml read successfully on 17 Aug.", action: "Keep only canonical live URLs.", lastUpdate: "17 Aug" },
      { measure: "HTTPS URLs", value: 13, status: "Pass", interpretation: "No non-HTTPS URL issue.", action: "Maintain redirects and HSTS.", lastUpdate: "21 Aug" },
      { measure: "Breadcrumbs", value: 4, status: "Pass", interpretation: "Four valid, zero invalid.", action: "Extend to new recipe/watch pages.", lastUpdate: "21 Aug" },
      { measure: "Manual actions", value: 0, status: "Pass", interpretation: "None detected.", action: "No action required.", lastUpdate: "21 Aug" },
      { measure: "Security issues", value: 0, status: "Pass", interpretation: "None detected.", action: "Continue monitoring.", lastUpdate: "21 Aug" },
    ],
    notIndexed: [
      { url: "http://otherpeoplesrecipes.co.uk/", reason: "Page with redirect", assessment: "Expected canonicalisation", treatment: "Keep permanent redirect to HTTPS canonical.", priority: "Monitor", observed: "6 Aug crawl" },
      { url: "http://www.otherpeoplesrecipes.co.uk/", reason: "Page with redirect", assessment: "Expected canonicalisation", treatment: "Keep permanent redirect.", priority: "Monitor", observed: "1 Aug crawl" },
      { url: "https://www.otherpeoplesrecipes.co.uk/", reason: "Page with redirect", assessment: "Expected canonicalisation", treatment: "Keep permanent redirect.", priority: "Monitor", observed: "1 Aug crawl" },
      { url: "/family-cookbook/dads-friday-night-butter-chicken", reason: "Page with redirect", assessment: "Healthy legacy redirect", treatment: "Keep redirect to current Butter Chicken slug.", priority: "Monitor", observed: "3 Aug crawl" },
      { url: "/family-cookbook/community/1", reason: "Discovered – not indexed", assessment: "Duplicate of Sudesh recipe", treatment: "301 or canonicalise to /family-cookbook/sudeshs-bhindi.", priority: "P1", observed: "Validation started 13 Aug" },
      { url: "/privacy", reason: "Discovered – not indexed", assessment: "Low search value", treatment: "Allow discovery; indexing is optional.", priority: "P3", observed: "Validation started 13 Aug" },
      { url: "/terms", reason: "Discovered – not indexed", assessment: "Low search value", treatment: "Allow discovery; indexing is optional.", priority: "P3", observed: "Validation started 13 Aug" },
    ],
    pageSpeed: [
      { metric: "Performance", value: 100, unit: "score", context: "Lighthouse lab score; not field data." },
      { metric: "Accessibility", value: 97, unit: "score", context: "Contrast and caption-track findings remain." },
      { metric: "Best Practices", value: 100, unit: "score", context: "No lab issue." },
      { metric: "SEO", value: 100, unit: "score", context: "Basic audit and structured data valid." },
      { metric: "First Contentful Paint", value: 0.9, unit: "seconds", context: "Emulated Moto G Power on Slow 4G." },
      { metric: "Largest Contentful Paint", value: 1.7, unit: "seconds", context: "Good lab result." },
      { metric: "Total Blocking Time", value: 0, unit: "milliseconds", context: "Excellent." },
      { metric: "Cumulative Layout Shift", value: 0, unit: "score", context: "Excellent." },
      { metric: "Speed Index", value: 1.8, unit: "seconds", context: "Strong lab result." },
    ],
    pageSpeedMeta: {
      testedUrl: "https://otherpeoplesrecipes.co.uk/",
      strategy: "mobile",
      fetchedAt: "2026-08-21T09:00:00.000Z",
      lighthouseVersion: null,
    },
    structuredData: [
      { area: "Recipe rich results", valid: 4, invalidOrExcluded: 0, finding: "Valid; optional fields are missing on some recipes.", action: "Add only verified prep/cook times, cuisine, keywords and instruction media. Never invent ratings or nutrition." },
      { area: "Breadcrumbs", valid: 4, invalidOrExcluded: 0, finding: "No issue in the last 90 days.", action: "Apply same pattern to future pages." },
      { area: "Video indexing", valid: 1, invalidOrExcluded: 2, finding: "One video is indexed and two pages report no indexed video.", action: "Create one dedicated, canonical watch page per priority film." },
      { area: "Video structured data", valid: 21, invalidOrExcluded: 0, finding: "Twenty-one valid video enhancement items are reported.", action: "Maintain valid VideoObject markup and add dedicated watch pages where appropriate." },
      { area: "Core Web Vitals", valid: 0, invalidOrExcluded: 0, finding: "No field data yet on mobile or desktop.", action: "Enable Vercel Speed Insights and wait for sufficient real users." },
    ],
    authority: [
      { measure: "External links", count: 13, breakdown: "All from otherpeoplesrecipes.com", implication: "The backlink profile is extremely thin.", action: "Earn relevant independent links to recipe and mission pages." },
      { measure: "Top externally linked page", count: 7, breakdown: "/family-cookbook", implication: "The hub receives most external links.", action: "Secure links directly to individual recipes too." },
      { measure: "Second linked page", count: 6, breakdown: "/cookies", implication: "Utility page attracts nearly half the links.", action: "Shift earned link equity toward editorial pages." },
      { measure: "Internal links", count: 15, breakdown: "/ 6; /family-cookbook 4; /cookies 3; /share 2", implication: "Recipe depth is underlinked.", action: "Add contextual recipe, story and film links." },
    ],
    note: "Search Console enhancements can lag recent code changes. Instruction names and featured-recipe timings already added in code may not be reflected until Google recrawls. Request validation only after the production version is confirmed.",
  },

  socialOverview: {
    platforms: [
      { platform: "Instagram", period: "30d to 21 Aug", views: 4838, viewers: 2173, interactions: 356, followers: 68, profileVisits: 230, outboundClicks: 2, websiteVisitors: "Not separately reported", interactionRate: 0.0736 },
      { platform: "Facebook", period: "24 Jul–20 Aug", views: 6600, viewers: 2428, interactions: 402, followers: 53, profileVisits: 344, outboundClicks: "Not reported", websiteVisitors: "Not separately reported", interactionRate: 0.0609 },
      { platform: "Pinterest", period: "22 Jul–21 Aug", views: 256, viewers: 113, interactions: 11, followers: "Not displayed", profileVisits: "Not reported", outboundClicks: 1, websiteVisitors: "Not separately reported", interactionRate: 0.043 },
      { platform: "YouTube", period: "24 Jul–20 Aug", views: 223, viewers: "Not reported", interactions: "2 Shorts likes", followers: 9, profileVisits: "Not reported", outboundClicks: "Not reported", websiteVisitors: "Not separately reported", interactionRate: 0.009 },
      { platform: "TikTok", period: "Last 28 days to 21 Aug", views: 5300, viewers: "Not reported", interactions: 44, followers: 4, profileVisits: 21, outboundClicks: "Not available", websiteVisitors: "Not separately reported", interactionRate: 0.0083 },
      { platform: "LinkedIn", period: "21 Jul–19 Aug (manually checked 21 Aug 2026, 09:45)", views: 126, viewers: "Not reported", interactions: 6, followers: 21, profileVisits: "Not reported", outboundClicks: "Not reported", websiteVisitors: "Not separately reported", interactionRate: 0.0476 },
    ],
    diagnosis: [
      { channel: "Instagram", strength: "4,838 views; 72.6% from non-followers; 356 interactions.", constraint: "230 profile visits produced only 2 external-link taps.", nextMove: "Keep the source-coded bio link prominent and strengthen every Reel end card.", workingKpi: "Profile-to-link click rate" },
      { channel: "Facebook", strength: "6.6K views, 2,428 viewers and 402 interactions.", constraint: "Current outbound-click reporting was not available in the overview.", nextMove: "Continue direct recipe links and repeat the strongest Dave & Rubble formats.", workingKpi: "Link clicks and referred visitors" },
      { channel: "Pinterest", strength: "256 impressions and 113 total audience; Ada's Jollof Pin leads with 113 impressions.", constraint: "Only 1 outbound click across the period.", nextMove: "Publish vertical, keyworded recipe pins linking to canonical recipes.", workingKpi: "Outbound clicks per 1,000 impressions" },
      { channel: "YouTube", strength: "223 views and subscriber count increased to 9.", constraint: "Only 16.5% of Shorts viewers stayed to watch; likes remain low.", nextMove: "Test stronger titles and a faster first-second hook.", workingKpi: "Stayed-to-watch rate and subscribers" },
      { channel: "TikTok", strength: "5.3K views; 89.8% of recent traffic from For You.", constraint: "Only 21 profile views and 4 total followers; one caption remains corrupted.", nextMove: "Clean the caption, strengthen on-screen CTA and measure bio clicks.", workingKpi: "Profile visit rate and followers per 1K views" },
      { channel: "LinkedIn", strength: "21 followers, 16 gained in the last 30 days; 126 impressions on posts.", constraint: "Page is brand new — no live API access yet, so this is a manual snapshot.", nextMove: "Keep posting weekly until Community Management API approval lands live data.", workingKpi: "Follower growth rate and post impressions" },
    ],
    note: "Facebook website visitors group facebook.com (32), m.facebook.com (10) and l.facebook.com (7). Referrer host totals are not necessarily deduplicated across hosts. Instagram, TikTok and YouTube in-app visits may appear as Direct when the referrer is stripped.",
  },

  platforms: {
    instagram: {
      handle: "@opr_uk",
      period: "Native professional dashboard · Last 30 days to 21 Aug 2026 · 27 posts",
      metrics: [
        { metric: "Views", value: "4,838", interpretation: "Total content views.", action: "Track weekly trend." },
        { metric: "Viewers", value: "2,173", interpretation: "Accounts that viewed content.", action: "Use as reach proxy." },
        { metric: "Interactions", value: "356", interpretation: "Content interactions.", action: "Repeat high-interaction formats." },
        { metric: "Accounts engaged", value: "57", interpretation: "Accounts that interacted.", action: "Build repeat engagement." },
        { metric: "Profile visits", value: "230", interpretation: "4.8% of views reached the profile.", action: "Make bio CTA unmistakable." },
        { metric: "External link taps", value: "2", interpretation: "Profile link taps reported by Instagram.", action: "Improve profile-to-site conversion." },
        { metric: "Followers", value: "68", interpretation: "Current follower count.", action: "Report net growth monthly." },
        { metric: "Non-follower share of views", value: "72.6%", interpretation: "Strong discovery beyond followers.", action: "Keep Reels-first cadence." },
        { metric: "Reels share of views", value: "84.0%", interpretation: "Reels dominate reach.", action: "Prioritise short video." },
      ],
      topContent: [
        { rank: 1, title: "Top ranked content card", value: "20 accounts engaged", extra: "", note: "Instagram's ranked web view did not expose the caption." },
        { rank: 2, title: "Second ranked content card", value: "19 accounts engaged", extra: "", note: "Ranked by accounts engaged." },
        { rank: 3, title: "Third ranked content card", value: "18 accounts engaged", extra: "", note: "Ranked by accounts engaged." },
        { rank: 4, title: "Fourth ranked content card", value: "17 accounts engaged", extra: "", note: "Ranked by accounts engaged." },
        { rank: 5, title: "Fifth ranked content card", value: "16 accounts engaged", extra: "", note: "Ranked by accounts engaged." },
      ],
      discoverySources: [],
      note: "Instagram reported 230 profile visits and 2 external-link taps. Reconcile these with source-coded first-party link events before treating them as website sessions.",
    },
    facebook: {
      handle: "Other People's Recipes",
      period: "Meta Business Suite · 24 Jul–20 Aug 2026",
      metrics: [
        { metric: "Views", value: "6,600", interpretation: "Content was viewed approximately 6.6K times.", action: "Maintain consistent Reel/post cadence." },
        { metric: "Viewers", value: "2,428", interpretation: "Unique viewer metric shown by Meta.", action: "Use for reach trend." },
        { metric: "Content interactions", value: "402", interpretation: "333 from followers; 69 from non-followers.", action: "Optimise for shares/comments." },
        { metric: "3-second video views", value: "1,500", interpretation: "Initial video attention.", action: "Improve first three seconds." },
        { metric: "Watch time", value: "10h 29m", interpretation: "Total watch time.", action: "Track watch time per video." },
        { metric: "Link clicks", value: "Not reported", interpretation: "Not available in the current overview.", action: "Use direct recipe URLs and UTMs." },
        { metric: "Net follows", value: "49", interpretation: "51 follows minus 2 unfollows.", action: "Build repeatable growth." },
        { metric: "Current followers", value: "53", interpretation: "Lifetime followers at collection.", action: "Demographics unlock at 100." },
      ],
      topContent: [
        { rank: 1, title: "Some recipes get adjusted", value: "295 views", extra: "16 interactions", note: "Strongest of the newly published Dave & Rubble posts." },
        { rank: 2, title: "Rubble's relationship with time", value: "168 views", extra: "12 interactions", note: "The joke-led format continues to travel." },
        { rank: 3, title: "Quality Control", value: "134 views", extra: "15 interactions", note: "High interaction relative to reach." },
        { rank: 4, title: "Gautam & Shobha · Dish of the Week", value: "78 views", extra: "9 interactions", note: "Published on 20 Aug; result is still moving." },
      ],
      discoverySources: [],
      note: "Meta's recommendation says 1–3 Reels per week. OPR published 19 pieces in the week reviewed (10 Facebook posts and 9 stories); prioritise quality and repeatable formats over volume alone.",
    },
    pinterest: {
      handle: "Other Peoples Recipes",
      period: "Pinterest Analytics · 22 Jul–21 Aug 2026 · 21 Pins in the OPR Family Recipes board",
      metrics: [
        { metric: "Impressions", value: "256", interpretation: "Pins shown on screen.", action: "Increase keyworded pin volume." },
        { metric: "Engagements", value: "11", interpretation: "Clicks and saves combined.", action: "Optimise titles and creative." },
        { metric: "Outbound clicks", value: "1", interpretation: "Click to destination URL.", action: "Direct every Pin to its recipe page." },
        { metric: "Saves", value: "1", interpretation: "Pins saved during the period.", action: "Create more save-worthy recipe cards." },
        { metric: "Total audience", value: "113", interpretation: "Pinners who saw or engaged.", action: "Early-stage reach." },
        { metric: "Engaged audience", value: "4", interpretation: "Pinners who engaged with OPR Pins.", action: "Track alongside total audience." },
        { metric: "Engagement rate", value: "4.3%", interpretation: "Engagements ÷ impressions.", action: "Directional benchmark." },
      ],
      topContent: [
        { rank: 1, title: "Ada's Party Jollof Rice | Nigerian Recipe", value: "113 impressions", extra: "44.1% of total", note: "Build more keyword-specific recipe pins." },
        { rank: 2, title: "Krishna Anand's Baingan Ka Bharta", value: "28 impressions", extra: "10.9% of total", note: "Use search-led title and ingredient image." },
        { rank: 3, title: "Dave's Butter Chicken | A family recipe from New Malden", value: "15 impressions", extra: "5.9% of total", note: "Link directly to canonical recipe." },
        { rank: 4, title: "Ada's Party Jollof Rice | OPR", value: "14 impressions", extra: "5.5% of total", note: "Test title variants without duplicating weak creative." },
        { rank: 5, title: "Quality Control", value: "10 impressions", extra: "3.9% of total", note: "Humour-led video is beginning to surface." },
      ],
      discoverySources: [],
      note: "Ada's primary Jollof Pin generated 44.1% of all recorded impressions. This is a clear early content signal, but the 256-impression sample remains too small for a firm conclusion.",
    },
    youtube: {
      handle: "OPR",
      period: "YouTube Studio · 24 Jul–20 Aug 2026 · 9 current subscribers",
      metrics: [
        { metric: "Views", value: "223", interpretation: "Total channel views in the selected period.", action: "Keep formats distinct in reporting." },
        { metric: "Watch time", value: "0.4 hours", interpretation: "Total estimated watch time.", action: "Grow with stronger packaging and retention." },
        { metric: "Net subscribers", value: "9", interpretation: "Growth in the 28-day period.", action: "Use explicit subscribe cue sparingly." },
        { metric: "Current subscribers", value: "9", interpretation: "Realtime count.", action: "Small base; percentages will be volatile." },
        { metric: "Impressions", value: "4,000", interpretation: "Thumbnail impressions.", action: "Strong opportunity to improve packaging." },
        { metric: "Impression CTR", value: "1.3%", interpretation: "4K impressions produced 54 views.", action: "Test stronger thumbnail/title promise." },
        { metric: "Published videos / Shorts", value: "14 / 9", interpretation: "Long-form vs short uploads.", action: "Prioritise strongest stories." },
        { metric: "Shorts stayed to watch", value: "16.5%", interpretation: "83.5% swiped away.", action: "Lead with the joke, result or emotional promise." },
      ],
      topContent: [
        { rank: 1, title: "Preserving Nani's Secret Baingan Bharta", value: "43 views", extra: "0:22 avg · 59.5% viewed", note: "Top long-form result; meaningful retention." },
        { rank: 2, title: "A New Menu Every Month | The OPR Vision", value: "43 views", extra: "0:08 avg · 75.3% viewed", note: "Strong short completion." },
        { rank: 3, title: "A Menu Written by the People | The OPR Vision", value: "43 views", extra: "0:07 avg · 71.8% viewed", note: "Comparable reach across the OPR vision series." },
        { rank: 4, title: "The OPR Idea | A Menu Written by the People", value: "14 views", extra: "0:07 avg · 65.5% viewed", note: "Packaging/distribution limited." },
        { rank: 5, title: "Other Peoples Recipes, Every Recipe has a Story", value: "13 views", extra: "0:08 avg · 75.9% viewed", note: "Good retention on a small sample." },
      ],
      discoverySources: [
        { source: "Shorts feed", share: 0.391, approxViews: 72, meaning: "Largest source.", action: "Improve first-second hook." },
        { source: "Suggested videos", share: 0.261, approxViews: 48, meaning: "YouTube recommendations.", action: "Create connected series/playlists." },
        { source: "Channel pages", share: 0.12, approxViews: 22, meaning: "Visitors browsing OPR.", action: "Improve channel homepage sections." },
        { source: "YouTube search", share: 0.098, approxViews: 18, meaning: "Search discovery.", action: "Use precise recipe titles/descriptions." },
        { source: "Other YouTube features", share: 0.054, approxViews: 10, meaning: "Miscellaneous internal surfaces.", action: "Monitor." },
        { source: "Other", share: 0.076, approxViews: 14, meaning: "Remaining sources.", action: "Monitor." },
      ],
      note: "A 1.3% impression CTR is the clearest YouTube constraint. A working target of 3–5% is a planning goal, not a forecast; judge it alongside average view duration so stronger packaging does not attract the wrong viewer.",
    },
    tiktok: {
      handle: "@opr_uk",
      period: "TikTok Studio · Last 28 days to 21 Aug 2026",
      metrics: [
        { metric: "Video views", value: "5,300", interpretation: "Strong native exposure across OPR short-form content.", action: "Convert discovery into profile/site action." },
        { metric: "Likes", value: "39", interpretation: "Primary visible engagement.", action: "Test stronger emotional/comedic payoffs." },
        { metric: "Comments", value: "1", interpretation: "Very low conversation.", action: "Ask specific, easy-to-answer recipe questions." },
        { metric: "Shares", value: "4", interpretation: "Early sharing signal.", action: "Create family-recognition moments." },
        { metric: "Profile views", value: "21", interpretation: "0.40% of video views reached the profile.", action: "Strengthen on-screen and caption CTA." },
        { metric: "Total followers", value: "4", interpretation: "Current total.", action: "Report per 1K views while small." },
      ],
      topContent: [
        { rank: 1, title: "The best kitchen helper has four paws", value: "812 views (28d)", extra: "813 all-time views", note: "Strongest current TikTok post." },
        { rank: 2, title: "Krishna Anand's Baingan ka Bharta", value: "389 views (28d)", extra: "390 all-time views", note: "Recipe-story framing performs strongly." },
        { rank: 3, title: "From Krishna Anand to the OPR cookbook", value: "361 views (28d)", extra: "362 all-time views", note: "Heritage-led recipe story." },
        { rank: 4, title: "OPR Jollof Rice", value: "357 views (28d)", extra: "358 all-time views", note: "Direct dish-led creative remains competitive." },
        { rank: 5, title: "Mummy Morris & Rubble: Beef Casserole", value: "242 views (7d)", extra: "246 all-time views", note: "Caption still contains accidental desktop/UI text and should be corrected." },
      ],
      discoverySources: [
        { source: "For You", share: 0.898, approxViews: 4759, meaning: "Excellent algorithmic discovery.", action: "" },
        { source: "Personal profile", share: 0.092, approxViews: 488, meaning: "Small returning/profile traffic.", action: "" },
        { source: "Search", share: 0.01, approxViews: 53, meaning: "Search contribution is minimal.", action: "" },
      ],
      note: "The public Mummy Morris caption includes appended interface text (for example app tabs and file names). This is a confirmed content-quality issue, not an analytics inference.",
    },
  },

  measurementActions: {
    linkClicks: [
      { linkKey: "founding-table", clicks: 1, firstClick: "17 Aug 10:11", lastClick: "17 Aug 10:11", status: "Legacy key", interpretation: "New label is Join Our Table; update the analytics key when practical." },
      { linkKey: "recipe-of-month", clicks: 1, firstClick: "17 Aug 10:21", lastClick: "17 Aug 10:21", status: "Current", interpretation: "Single launch-day click." },
    ],
    gaps: [
      { gap: "Social source attribution", currentState: "Implemented for Instagram, TikTok, Facebook, YouTube, Pinterest and LinkedIn.", risk: "Profile URLs must use their matching src parameter.", fix: "Use /links?src=platform on every social profile.", priority: "Closed", owner: "Site + social", due: "Live" },
      { gap: "Campaign attribution", currentState: "UTMs are retained first-party and grouped in the private dashboard.", risk: "Uncoded campaign links remain unattributed.", fix: "Use a stable utm_campaign value on every campaign link.", priority: "Closed", owner: "Site + social", due: "Live" },
      { gap: "Real-user performance", currentState: "Vercel Speed Insights collection enabled.", risk: "Field data takes time to accumulate.", fix: "Review route-level Core Web Vitals at each month-end.", priority: "Closed", owner: "Site", due: "Live" },
      { gap: "Conversion events", currentState: "Privacy-safe server-side conversion totals are live.", risk: "Only explicitly defined success events are counted.", fix: "Review the conversion allow-list when new participation flows launch.", priority: "Closed", owner: "Site", due: "Live" },
      { gap: "Cross-platform comparison", currentState: "Formal comparisons now use complete calendar months; rolling figures are labelled interim.", risk: "Platforms still define reach and interactions differently.", fix: "Close each report at month-end and compare like-for-like metrics only.", priority: "Closed", owner: "Analytics", due: "Month-end" },
    ],
    deliveryPlan: [
      { priority: "P1", workstream: "Measurement", action: "Keep every social bio and campaign link source-coded.", baseline: "First-party source and UTM capture live", goal30d: "All profiles coded", goal90d: "Monthly source-to-site report", owner: "Site/social", timing: "Ongoing", status: "Live" },
      { priority: "P1", workstream: "Authority", action: "Earn relevant independent backlinks.", baseline: "Outreach list and three personalised pitches prepared", goal30d: "3 approved pitches/week", goal90d: "10+ new relevant domains", owner: "PR/content", timing: "Weekly", status: "Ready for approval" },
      { priority: "P1", workstream: "Indexing", action: "Validate the community/1 consolidation in Search Console.", baseline: "Permanent redirect live; duplicate removed from sitemap", goal30d: "Redirect validated", goal90d: "Coverage resolved", owner: "Site", timing: "After deployment", status: "Implemented" },
      { priority: "P1", workstream: "Video SEO", action: "Monitor dedicated watch pages and video sitemap coverage.", baseline: "21 watch pages with VideoObject data and transcripts", goal30d: "Priority pages discovered", goal90d: "Priority film library eligible", owner: "Site/content", timing: "Monthly", status: "Implemented" },
      { priority: "P1", workstream: "TikTok hygiene", action: "Remove/repost the Beef Casserole film using the approved clean caption.", baseline: "Corrected caption, tagged link and checklist prepared", goal30d: "Clean post live", goal90d: "Pre-publish checklist adopted", owner: "Social", timing: "Next account session", status: "External action pending" },
      { priority: "P2", workstream: "YouTube", action: "Test stronger titles and thumbnails.", baseline: "CTR 1.3%", goal30d: "Two controlled tests", goal90d: "Working CTR 3–5% with retention protected", owner: "Video", timing: "Fortnightly", status: "Not started" },
      { priority: "P2", workstream: "Recipe SEO", action: "Expand verified recipe data and helpful copy.", baseline: "4 valid Recipe items", goal30d: "Bhindi + Jollof refresh", goal90d: "All priority recipes complete", owner: "Content", timing: "Monthly", status: "Not started" },
      { priority: "P2", workstream: "Instagram", action: "Convert profile visits with /links and pinned CTA.", baseline: "174 profile visits; clicks unavailable", goal30d: "Tracking live", goal90d: "Improving profile-to-link rate", owner: "Social", timing: "Week 1", status: "Not started" },
      { priority: "P2", workstream: "Pinterest", action: "Publish search-led vertical recipe Pins.", baseline: "126 impressions; 1 outbound", goal30d: "2 Pins/recipe", goal90d: "Consistent outbound growth", owner: "Social/content", timing: "Weekly", status: "Not started" },
      { priority: "P2", workstream: "Accessibility", action: "Fix contrast and add caption tracks.", baseline: "Lighthouse accessibility 97", goal30d: "Issues fixed", goal90d: "Score 100 maintained", owner: "Site", timing: "30 days", status: "Not started" },
      { priority: "P2", workstream: "Performance", action: "Review Vercel Speed Insights at month-end.", baseline: "Collection enabled", goal30d: "First field baseline", goal90d: "Monthly CWV baseline", owner: "Site", timing: "Monthly", status: "Live" },
      { priority: "P3", workstream: "Reporting", action: "Repeat this workbook at month-end.", baseline: "First baseline", goal30d: "August close", goal90d: "Three-month trend", owner: "Analytics", timing: "Monthly", status: "Scheduled" },
    ],
    note: "Only two clicks have been recorded since /links launched on 17 August. These may include implementation QA, so they are not yet evidence of audience behaviour. Do not buy bulk backlinks, fabricate reviews/ratings, or add invented nutrition/timing data.",
  },
};
