import "server-only";
import type { AnalyticsReport } from "./analytics-report-types";

// Manually exported from each platform's native dashboard and Google/Vercel
// tooling, 17 August 2026. Regenerate this file the same way next time the
// report is refreshed (see Sources & Definitions in the source workbook for
// exactly which dashboard each figure came from) — there is no live API
// behind most of these numbers yet. The Google Search figures at the top of
// the admin dashboard are the exception: those come from a live Search
// Console connection (see lib/google-search-console.ts) and intentionally
// are NOT read from this file, to avoid showing stale numbers next to a
// live source.
export const analyticsReport: AnalyticsReport = {
  preparedDate: "2026-08-17",
  executiveSummary: {
    preparedDate: "2026-08-17",
    kpis: [
      { label: "Website visitors · 30d", value: "294" },
      { label: "Page views · 30d", value: "1,836" },
      { label: "Google clicks", value: "22" },
      { label: "Google CTR", value: "37.3%" },
      { label: "Indexed pages", value: "16" },
      { label: "Mobile SEO score", value: "100" },
      { label: "Social exposures*", value: "13,662" },
      { label: "Facebook referrals", value: "49" },
      { label: "Site action events", value: "26" },
      { label: "Accessibility score", value: "97" },
    ],
    whatTheNumbersSay: [
      {
        area: "Website",
        evidence: "294 visitors generated 1,836 page views; 46% bounce rate.",
        meaning: "The early audience explores deeply (6.24 pages per visitor).",
        decision: "Protect the fast site experience and make calls to action measurable.",
      },
      {
        area: "Google Search",
        evidence: "22 clicks from 59 impressions; 37.3% CTR; average position 7.6.",
        meaning: "Very small sample, but strong relevance when OPR appears.",
        decision: "Grow impressions with recipe-led content and authoritative backlinks.",
      },
      {
        area: "Social discovery",
        evidence: "Instagram: 74.4% of views from non-followers. TikTok: 96.1% from For You.",
        meaning: "Short-form content is reaching beyond existing audiences.",
        decision: "Use stronger profile and end-card calls to action to convert discovery into site visits.",
      },
      {
        area: "Social traffic",
        evidence: "Facebook hostnames supplied 49 website visitors; Meta reports 15 Facebook link clicks.",
        meaning: "Facebook is the clearest social-to-site pathway today.",
        decision: "Keep direct recipe links in Facebook posts and apply source tracking everywhere.",
      },
      {
        area: "Technical SEO",
        evidence: "Sitemap succeeds; HTTPS and breadcrumbs are healthy; Lighthouse SEO 100.",
        meaning: "The technical foundation is strong.",
        decision: "Focus effort on authority, recipe discovery and video watch pages—not a redesign.",
      },
      {
        area: "Measurement",
        evidence: "Only two /links button clicks are logged, both on launch day and possibly QA.",
        meaning: "The link page is too new to judge and cannot yet identify source platform.",
        decision: "Give each social a source-coded bio URL and log the source with every click.",
      },
    ],
    topPriorities: [
      { priority: "P1", action: "Add source-coded /links URLs and UTMs for every social profile and campaign.", whyNow: "Instagram, TikTok and YouTube referrals are not separately visible in website analytics.", successMeasure: "Every profile/campaign has a distinct source; monthly report reconciles clicks with visits.", owner: "Site + social · this week" },
      { priority: "P1", action: "Earn links from contributors, local press, food-history groups and relevant partners.", whyNow: "Only 13 external links are reported—and all are from the sister .com domain.", successMeasure: "10+ new relevant referring domains, each linking to a useful canonical page.", owner: "PR/content · weekly" },
      { priority: "P1", action: "Consolidate /family-cookbook/community/1 into the canonical Sudesh recipe URL.", whyNow: "Google discovered the duplicate but has not indexed it.", successMeasure: "Duplicate removed from coverage; canonical recipe remains indexable.", owner: "Site · this week" },
      { priority: "P1", action: "Create dedicated film watch pages with VideoObject data, transcripts and a video sitemap.", whyNow: "Homepage video is excluded because it is not on a watch page; only two videos are indexed.", successMeasure: "Each priority film has an indexable watch page and valid video data.", owner: "Site/content · 30 days" },
      { priority: "P1", action: "Remove/repost the TikTok caption containing accidental desktop interface text.", whyNow: "The caption is publicly untidy and weakens trust.", successMeasure: "Correct caption live; post checked on mobile and desktop.", owner: "Social · today" },
      { priority: "P2", action: "Improve YouTube titles and thumbnails; test one promise-led creative pattern.", whyNow: "4,000 impressions produced a 1.3% click-through rate.", successMeasure: "CTR moves towards a 3–5% working target without reducing retention.", owner: "Video · fortnightly" },
      { priority: "P2", action: "Turn search interest in bhindi and jollof into richer recipe-page coverage.", whyNow: "These are the clearest visible non-brand query themes.", successMeasure: "More recipe-page impressions and first clicks for non-brand searches.", owner: "Content · 2 articles/month" },
      { priority: "P2", action: "Enable Vercel Speed Insights; fix contrast and caption-track warnings.", whyNow: "No field performance data exists yet; Lighthouse accessibility is 97 rather than 100.", successMeasure: "Real-user performance starts collecting; accessibility checks pass.", owner: "Site · this week" },
    ],
    footnote: "*Social exposures add platform-reported views/impressions and are not deduplicated people. Native platform definitions and date windows differ; use this as an activity indicator, not total audience reach.",
  },

  website: {
    period: "Vercel Web Analytics · 30 days: 18 Jul–17 Aug 2026 · 7 days: 10–17 Aug 2026",
    core: [
      { metric: "Visitors", last30Days: 294, last7Days: 117, change7d: -0.13 },
      { metric: "Page views", last30Days: 1836, last7Days: 749, change7d: -0.16 },
      { metric: "Bounce rate", last30Days: 0.46, last7Days: 0.42, change7d: -0.07 },
      { metric: "Pages per visitor", last30Days: 6.24, last7Days: 6.4, change7d: null },
    ],
    topPages: [
      { path: "/", visitors: 196, role: "Homepage", seoNote: "Dominant landing page and 17 of 22 organic clicks." },
      { path: "/family-cookbook", visitors: 95, role: "Living Cookbook hub", seoNote: "Second-largest audience and 3 organic clicks." },
      { path: "/founder", visitors: 62, role: "Brand story", seoNote: "One organic click; strong early exploration." },
      { path: "/films", visitors: 57, role: "Film collection", seoNote: "One organic click; priority for dedicated watch pages." },
      { path: "/share", visitors: 43, role: "Recipe submission", seoNote: "12 search impressions but no clicks yet." },
      { path: "/our-story", visitors: 39, role: "Legacy URL", seoNote: "Old name still present in historical traffic/search data; retain 301." },
      { path: "/founding-table", visitors: 35, role: "Legacy URL", seoNote: "Old name still present in search data; retain 301 to Join Our Table." },
    ],
    topReferrers: [
      { host: "google.com", visitors: 35, channel: "Google", observation: "Largest single referrer host.", action: "Expand non-brand recipe discovery." },
      { host: "facebook.com", visitors: 32, channel: "Facebook", observation: "Main Facebook hostname.", action: "Keep direct recipe links." },
      { host: "m.facebook.com", visitors: 10, channel: "Facebook", observation: "Mobile Facebook traffic.", action: "Use mobile-first landing pages." },
      { host: "l.facebook.com", visitors: 7, channel: "Facebook", observation: "Facebook link shim.", action: "Use campaign/source tracking." },
      { host: "com.linkedin.android", visitors: 2, channel: "LinkedIn", observation: "Small early referral source.", action: "Use founder/mission stories." },
      { host: "uk.pinterest.com", visitors: 2, channel: "Pinterest", observation: "Early discovery traffic.", action: "Create vertical recipe pins." },
      { host: "vercel.com", visitors: 2, channel: "Technical", observation: "Likely preview/deployment traffic.", action: "Exclude from marketing decisions." },
    ],
    audienceCountry: [
      { country: "United Kingdom", share: 0.51, visitors: 150 },
      { country: "United States", share: 0.21, visitors: 62 },
      { country: "Greece", share: 0.11, visitors: 32 },
      { country: "Brazil", share: 0.05, visitors: 15 },
      { country: "India", share: 0.04, visitors: 12 },
      { country: "Other", share: 0.08, visitors: 24 },
    ],
    audienceDevice: [
      { device: "Mobile", share: 0.63 },
      { device: "Desktop", share: 0.36 },
      { device: "Tablet", share: 0.01 },
    ],
    audienceOS: [
      { os: "iOS", share: 0.49, visitors: 144 },
      { os: "Mac", share: 0.21, visitors: 62 },
      { os: "Android", share: 0.15, visitors: 44 },
      { os: "Windows", share: 0.11, visitors: 32 },
      { os: "Linux", share: 0.03, visitors: 9 },
    ],
    note: "Action-event rates divide events by visitors; they are not unique-user conversion rates and a person may complete more than one action. Vercel Hobby does not expose UTM reports or custom events.",
  },

  googleSearch: {
    period: "Google Search Console · Data available 1–15 Aug 2026",
    kpis: [
      { metric: "Clicks", value: 22, definition: "Visits from Google Search", read: "Small but genuine organic demand." },
      { metric: "Impressions", value: 59, definition: "Times an OPR result appeared", read: "The main growth constraint is visibility." },
      { metric: "CTR", value: 0.373, definition: "Clicks ÷ impressions", read: "High, but based on a small sample." },
      { metric: "Average position", value: 7.6, definition: "Mean highest position", read: "Page-one average; query mix is limited." },
      { metric: "Indexed pages", value: 16, definition: "URLs eligible to appear", read: "69.6% of known URLs." },
      { metric: "Not indexed", value: 7, definition: "Known URLs not indexed", read: "Four redirects; three discovered/not indexed." },
    ],
    daily: [
      { date: "01 Aug", clicks: 0, impressions: 0, ctr: 0 },
      { date: "02 Aug", clicks: 3, impressions: 5, ctr: 0.6 },
      { date: "03 Aug", clicks: 1, impressions: 1, ctr: 1 },
      { date: "04 Aug", clicks: 1, impressions: 1, ctr: 1 },
      { date: "05 Aug", clicks: 0, impressions: 2, ctr: 0 },
      { date: "06 Aug", clicks: 3, impressions: 7, ctr: 0.43 },
      { date: "07 Aug", clicks: 2, impressions: 6, ctr: 0.33 },
      { date: "08 Aug", clicks: 1, impressions: 4, ctr: 0.25 },
      { date: "09 Aug", clicks: 0, impressions: 1, ctr: 0 },
      { date: "10 Aug", clicks: 1, impressions: 1, ctr: 1 },
      { date: "11 Aug", clicks: 4, impressions: 10, ctr: 0.4 },
      { date: "12 Aug", clicks: 2, impressions: 7, ctr: 0.29 },
      { date: "13 Aug", clicks: 0, impressions: 5, ctr: 0 },
      { date: "14 Aug", clicks: 2, impressions: 5, ctr: 0.4 },
      { date: "15 Aug", clicks: 2, impressions: 4, ctr: 0.5 },
    ],
    queries: [
      { query: "bhindi recipe", clicks: 0, impressions: 4 },
      { query: "3 cheese truffle charity bread", clicks: 0, impressions: 2 },
      { query: "bhindi ki recipe", clicks: 0, impressions: 1 },
      { query: "how to cook bhindi", clicks: 0, impressions: 1 },
      { query: "letter from our founder", clicks: 0, impressions: 1 },
      { query: "sam the cooking guy shepherd's pie", clicks: 0, impressions: 1 },
      { query: "Long-form jollof search (privacy-trimmed)", clicks: 0, impressions: 1 },
      { query: "Second long-form jollof search", clicks: 0, impressions: 1 },
    ],
    pages: [
      { page: "/", clicks: 17, impressions: 37 },
      { page: "/family-cookbook", clicks: 3, impressions: 19 },
      { page: "/films", clicks: 1, impressions: 12 },
      { page: "/founder", clicks: 1, impressions: 3 },
      { page: "http://otherpeoplesrecipes.co.uk/", clicks: 1, impressions: 2 },
      { page: "/share", clicks: 0, impressions: 12 },
      { page: "/our-story", clicks: 0, impressions: 11 },
      { page: "/family-cookbook/sudeshs-bhindi", clicks: 0, impressions: 8 },
      { page: "/family-cookbook/adas-jollof-rice", clicks: 0, impressions: 4 },
      { page: "/family-cookbook/krishna-anands-baingan-ka-bharta", clicks: 0, impressions: 4 },
      { page: "/family-cookbook/barbaras-beef-casserole", clicks: 0, impressions: 3 },
      { page: "/family-cookbook/nana-serbs-sunday-rice-pudding", clicks: 0, impressions: 2 },
      { page: "/family-cookbook/daves-butter-chicken", clicks: 0, impressions: 2 },
      { page: "/family-cookbook/sams-shepherds-pie", clicks: 0, impressions: 2 },
      { page: "/family-cookbook/phils-and-serbs-three-cheese-souffle", clicks: 0, impressions: 2 },
      { page: "/founding-table", clicks: 0, impressions: 1 },
    ],
    countries: [
      { country: "United Kingdom", clicks: 17, impressions: 27 },
      { country: "Greece", clicks: 3, impressions: 13 },
      { country: "Ireland", clicks: 1, impressions: 1 },
      { country: "Portugal", clicks: 1, impressions: 1 },
      { country: "India", clicks: 0, impressions: 7 },
      { country: "United States", clicks: 0, impressions: 4 },
      { country: "Canada", clicks: 0, impressions: 2 },
      { country: "Italy", clicks: 0, impressions: 1 },
      { country: "Saudi Arabia", clicks: 0, impressions: 1 },
      { country: "Pakistan", clicks: 0, impressions: 1 },
      { country: "Thailand", clicks: 0, impressions: 1 },
    ],
    devices: [
      { device: "Mobile", clicks: 17, impressions: 35 },
      { device: "Desktop", clicks: 5, impressions: 24 },
      { device: "Recipe Gallery", clicks: 0, impressions: 6 },
      { device: "Recipe rich result", clicks: 0, impressions: 2 },
    ],
    note: "Google withholds or anonymises many query rows for privacy, so visible queries do not reconcile to the 22 total clicks. Page-level counts can overlap when more than one OPR result appears for a search.",
  },

  seoTechnical: {
    asOf: "2026-08-17",
    indexing: [
      { measure: "Indexed URLs", value: 16, status: "Healthy base", interpretation: "16 of 23 known URLs are indexed.", action: "Monitor as the site grows.", lastUpdate: "14 Aug" },
      { measure: "Not indexed", value: 7, status: "Review", interpretation: "Four redirects and three discovered/not indexed.", action: "Resolve true duplicate and validate.", lastUpdate: "14 Aug" },
      { measure: "Sitemap discovered pages", value: 17, status: "Success", interpretation: "sitemap.xml read successfully on 17 Aug.", action: "Keep only canonical live URLs.", lastUpdate: "17 Aug" },
      { measure: "HTTPS URLs", value: 13, status: "Pass", interpretation: "No non-HTTPS URL issue.", action: "Maintain redirects and HSTS.", lastUpdate: "17 Aug" },
      { measure: "Breadcrumbs", value: 4, status: "Pass", interpretation: "Four valid, zero invalid.", action: "Extend to new recipe/watch pages.", lastUpdate: "16 Aug" },
      { measure: "Manual actions", value: 0, status: "Pass", interpretation: "None detected.", action: "No action required.", lastUpdate: "17 Aug" },
      { measure: "Security issues", value: 0, status: "Pass", interpretation: "None detected.", action: "Continue monitoring.", lastUpdate: "17 Aug" },
    ],
    notIndexed: [
      { url: "http://otherpeoplesrecipes.co.uk/", reason: "Page with redirect", assessment: "Expected canonicalisation", treatment: "Keep permanent redirect to HTTPS canonical.", priority: "Monitor", observed: "6 Aug crawl" },
      { url: "http://www.otherpeoplesrecipes.co.uk/", reason: "Page with redirect", assessment: "Expected canonicalisation", treatment: "Keep permanent redirect.", priority: "Monitor", observed: "1 Aug crawl" },
      { url: "https://www.otherpeoplesrecipes.co.uk/", reason: "Page with redirect", assessment: "Expected canonicalisation", treatment: "Keep permanent redirect.", priority: "Monitor", observed: "1 Aug crawl" },
      { url: "/family-cookbook/dads-friday-night-butter-chicken", reason: "Page with redirect", assessment: "Healthy legacy redirect", treatment: "Keep redirect to current Butter Chicken slug.", priority: "Monitor", observed: "3 Aug crawl" },
      { url: "/family-cookbook/community/1", reason: "Discovered – not indexed", assessment: "Duplicate of Sudesh recipe", treatment: "301 or canonicalise to /family-cookbook/sudeshs-bhindi.", priority: "P1", observed: "Validation started 13 Aug" },
      { url: "/privacy", reason: "Discovered – not indexed", assessment: "Low search value", treatment: "Allow discovery; indexing is optional.", priority: "P3", observed: "Validation started 13 Aug" },
      { url: "/terms", reason: "Discovered – not indexed", assessment: "Low search value", treatment: "Allow discovery; indexing is optional.", priority: "P3", observed: "Validation started 13 Aug" },
    ],
    pageSpeed: [
      { metric: "Performance", value: 100, unit: "score", context: "Lighthouse lab score; not field data." },
      { metric: "Accessibility", value: 97, unit: "score", context: "Contrast and caption-track findings remain." },
      { metric: "Best Practices", value: 100, unit: "score", context: "No lab issue." },
      { metric: "SEO", value: 100, unit: "score", context: "Basic audit and structured data valid." },
      { metric: "First Contentful Paint", value: 0.9, unit: "seconds", context: "Emulated Moto G Power on Slow 4G." },
      { metric: "Largest Contentful Paint", value: 1.7, unit: "seconds", context: "Good lab result." },
      { metric: "Total Blocking Time", value: 0, unit: "milliseconds", context: "Excellent." },
      { metric: "Cumulative Layout Shift", value: 0, unit: "score", context: "Excellent." },
      { metric: "Speed Index", value: 1.8, unit: "seconds", context: "Strong lab result." },
    ],
    structuredData: [
      { area: "Recipe rich results", valid: 4, invalidOrExcluded: 0, finding: "Valid; optional fields are missing on some recipes.", action: "Add only verified prep/cook times, cuisine, keywords and instruction media. Never invent ratings or nutrition." },
      { area: "Breadcrumbs", valid: 4, invalidOrExcluded: 0, finding: "No issue in the last 90 days.", action: "Apply same pattern to future pages." },
      { area: "Video indexing", valid: 2, invalidOrExcluded: 1, finding: "Homepage video excluded: video is not on a watch page.", action: "Create one dedicated, canonical watch page per priority film." },
      { area: "Video sitemap discovery", valid: 0, invalidOrExcluded: 0, finding: "Page sitemap reports zero discovered videos.", action: "Add video sitemap or robust VideoObject markup for watch pages." },
      { area: "Core Web Vitals", valid: 0, invalidOrExcluded: 0, finding: "No field data yet on mobile or desktop.", action: "Enable Vercel Speed Insights and wait for sufficient real users." },
    ],
    authority: [
      { measure: "External links", count: 13, breakdown: "All from otherpeoplesrecipes.com", implication: "The backlink profile is extremely thin.", action: "Earn relevant independent links to recipe and mission pages." },
      { measure: "Top externally linked page", count: 7, breakdown: "/family-cookbook", implication: "The hub receives most external links.", action: "Secure links directly to individual recipes too." },
      { measure: "Second linked page", count: 6, breakdown: "/cookies", implication: "Utility page attracts nearly half the links.", action: "Shift earned link equity toward editorial pages." },
      { measure: "Internal links", count: 15, breakdown: "/ 6; /family-cookbook 4; /cookies 3; /share 2", implication: "Recipe depth is underlinked.", action: "Add contextual recipe, story and film links." },
    ],
    note: "Search Console enhancements can lag recent code changes. Instruction names and featured-recipe timings already added in code may not be reflected until Google recrawls. Request validation only after the production version is confirmed.",
  },

  socialOverview: {
    platforms: [
      { platform: "Instagram", period: "30d to 17 Aug", views: 3252, viewers: 1604, interactions: 173, followers: 56, profileVisits: 174, outboundClicks: "Not reported", websiteVisitors: "Not separately reported", interactionRate: 0.0532 },
      { platform: "Facebook", period: "20 Jul–16 Aug", views: 5400, viewers: 2073, interactions: 225, followers: 42, profileVisits: 243, outboundClicks: 15, websiteVisitors: 49, interactionRate: 0.0417 },
      { platform: "Pinterest", period: "18 Jul–17 Aug", views: 126, viewers: 17, interactions: 8, followers: "Not displayed", profileVisits: "Not reported", outboundClicks: 1, websiteVisitors: 2, interactionRate: 0.0635 },
      { platform: "YouTube", period: "20 Jul–16 Aug", views: 184, viewers: "Not reported", interactions: "2 Shorts likes", followers: 4, profileVisits: "Not reported", outboundClicks: "Not reported", websiteVisitors: "Not separately reported", interactionRate: null },
      { platform: "TikTok", period: "Last 28 days", views: 4700, viewers: "Not reported", interactions: 38, followers: 3, profileVisits: 18, outboundClicks: "Not available", websiteVisitors: "Not separately reported", interactionRate: 0.0081 },
    ],
    diagnosis: [
      { channel: "Instagram", strength: "3,252 views; 74.4% non-followers; Reels drive 81.8%.", constraint: "174 profile visits but no external-link metric reported.", nextMove: "Set /links as the bio destination, pin a clear CTA, track source.", workingKpi: "Profile-to-link click rate" },
      { channel: "Facebook", strength: "5.4K views, 2,073 viewers, 225 interactions and 15 link clicks.", constraint: "Follows are front-loaded; audience is still small.", nextMove: "Continue direct recipe links and repeat best-performing family-film formats.", workingKpi: "Link clicks and referred visitors" },
      { channel: "Pinterest", strength: "Ada's Jollof Pin produces 43 of 126 impressions.", constraint: "Only 1 outbound click; overall audience 17.", nextMove: "Publish vertical, keyworded recipe pins linking to canonical recipes.", workingKpi: "Outbound clicks per 1,000 impressions" },
      { channel: "YouTube", strength: "4K impressions; some videos retain 59–91% of duration.", constraint: "1.3% impression CTR; 16.5% of Shorts viewers stay to watch.", nextMove: "Test stronger thumbnails/titles and a faster first-second hook.", workingKpi: "CTR and stayed-to-watch rate" },
      { channel: "TikTok", strength: "4.7K views; 96.1% from For You.", constraint: "Only 18 profile visits and 3 followers; one caption is corrupted.", nextMove: "Clean the caption, strengthen on-screen CTA and measure bio clicks.", workingKpi: "Profile visit rate and followers per 1K views" },
    ],
    note: "Facebook website visitors group facebook.com (32), m.facebook.com (10) and l.facebook.com (7). Referrer host totals are not necessarily deduplicated across hosts. Instagram, TikTok and YouTube in-app visits may appear as Direct when the referrer is stripped.",
  },

  platforms: {
    instagram: {
      handle: "@opr_uk",
      period: "Native professional dashboard · Last 30 days to 17 Aug 2026 · 24 posts",
      metrics: [
        { metric: "Views", value: "3,252", interpretation: "Total content views.", action: "Track weekly trend." },
        { metric: "Viewers", value: "1,604", interpretation: "Accounts that viewed content.", action: "Use as reach proxy." },
        { metric: "Interactions", value: "173", interpretation: "Content interactions.", action: "Repeat high-interaction formats." },
        { metric: "Accounts engaged", value: "30", interpretation: "Accounts that interacted.", action: "Build repeat engagement." },
        { metric: "Profile visits", value: "174", interpretation: "5.4% of views reached the profile.", action: "Make bio CTA unmistakable." },
        { metric: "Followers", value: "56", interpretation: "Current follower count.", action: "Report net growth monthly." },
        { metric: "Non-follower share of views", value: "74.4%", interpretation: "Strong discovery beyond followers.", action: "Keep Reels-first cadence." },
        { metric: "Reels share of views", value: "81.8%", interpretation: "Reels dominate reach.", action: "Prioritise short video." },
      ],
      topContent: [
        { rank: 1, title: "Reel · 14 Aug", value: "386 views", extra: "", note: "Dashboard card did not expose the caption in the ranked view." },
        { rank: 2, title: "Reel · 17 Aug", value: "217 views", extra: "", note: "Very recent; count still moving." },
        { rank: 3, title: "Reel · 1 Aug", value: "208 views", extra: "", note: "Established early performer." },
        { rank: 4, title: "Reel · 14 Aug", value: "186 views", extra: "", note: "Second strong 14 Aug Reel." },
        { rank: 5, title: "Reel · 13 Aug", value: "179 views", extra: "", note: "Top-five view count." },
      ],
      discoverySources: [],
      note: "Instagram reported 174 profile visits but did not display external link taps in the account panel. Treat clicks as unavailable—not zero—until source-coded bio traffic is collected.",
    },
    facebook: {
      handle: "Other People's Recipes",
      period: "Meta Business Suite · 20 Jul–16 Aug 2026",
      metrics: [
        { metric: "Views", value: "5,400", interpretation: "Content was viewed approximately 5.4K times.", action: "Maintain consistent Reel/post cadence." },
        { metric: "Viewers", value: "2,073", interpretation: "Unique viewer metric shown by Meta.", action: "Use for reach trend." },
        { metric: "Content interactions", value: "225", interpretation: "164 from followers; 61 from non-followers.", action: "Optimise for shares/comments." },
        { metric: "3-second video views", value: "1,100", interpretation: "Initial video attention.", action: "Improve first three seconds." },
        { metric: "Watch time", value: "8h 59m", interpretation: "Total watch time.", action: "Track watch time per video." },
        { metric: "Link clicks", value: "15", interpretation: "Native Facebook link clicks.", action: "Use direct recipe URLs and UTMs." },
        { metric: "Net follows", value: "37", interpretation: "39 follows minus 2 unfollows.", action: "Build repeatable growth." },
        { metric: "Current followers", value: "42", interpretation: "Lifetime followers at collection.", action: "Demographics unlock at 100." },
      ],
      topContent: [
        { rank: 1, title: "Dave's Butter Chicken", value: "298 views", extra: "8 reactions, 1 comment", note: "Best of the four recent named posts." },
        { rank: 2, title: "Dave & Rubble attempt Sam's Soufflé", value: "291 views", extra: "6 reactions", note: "Comparable reach; lighter interaction." },
        { rank: 3, title: "The Secret Ingredient", value: "92 views", extra: "1 reaction", note: "Too recent for a settled result." },
        { rank: 4, title: "Quality Control", value: "88 views", extra: "", note: "Too recent for a settled result." },
      ],
      discoverySources: [],
      note: "Meta's recommendation says 1–3 Reels per week. OPR published 19 pieces in the week reviewed (10 Facebook posts and 9 stories); prioritise quality and repeatable formats over volume alone.",
    },
    pinterest: {
      handle: "Other Peoples Recipes",
      period: "Pinterest Analytics · 18 Jul–17 Aug 2026 · 19 Pins in the OPR Family Recipes board",
      metrics: [
        { metric: "Impressions", value: "126", interpretation: "Pins shown on screen.", action: "Increase keyworded pin volume." },
        { metric: "Engagements", value: "8", interpretation: "Clicks and saves combined.", action: "Optimise titles and creative." },
        { metric: "Outbound clicks", value: "1", interpretation: "Click to destination URL.", action: "Direct every Pin to its recipe page." },
        { metric: "Total audience", value: "17", interpretation: "Pinners who saw or engaged.", action: "Early-stage reach." },
        { metric: "Monthly profile views", value: "59", interpretation: "Profile-level monthly view display.", action: "Track alongside Analytics." },
        { metric: "Engagement rate", value: "6.3%", interpretation: "Engagements ÷ impressions.", action: "Directional benchmark." },
      ],
      topContent: [
        { rank: 1, title: "Ada's Party Jollof Rice | Nigerian Recipe", value: "43 impressions", extra: "34.1% of total", note: "Build more keyword-specific recipe pins." },
        { rank: 2, title: "Krishna Anand's Baingan Ka Bharta", value: "12 impressions", extra: "9.5% of total", note: "Use search-led title and ingredient image." },
        { rank: 3, title: "Dave's Butter Chicken | A family recipe from New Malden", value: "10 impressions", extra: "7.9% of total", note: "Link directly to canonical recipe." },
        { rank: 4, title: "Ada's Party Jollof Rice | OPR", value: "7 impressions", extra: "5.6% of total", note: "Test title variants without duplicating weak creative." },
        { rank: 5, title: "Sam & Nadine's Shepherd's Pie | OPR", value: "7 impressions", extra: "5.6% of total", note: "Add save-worthy step/ingredient overlay." },
      ],
      discoverySources: [],
      note: "Ada's primary Jollof Pin generated 34.1% of all recorded impressions. This is a clear early content signal, but the 126-impression sample remains too small for a firm conclusion.",
    },
    youtube: {
      handle: "OPR",
      period: "YouTube Studio · 20 Jul–16 Aug 2026 · 4 current subscribers",
      metrics: [
        { metric: "Views", value: "184", interpretation: "92 videos and 92 Shorts.", action: "Keep formats distinct in reporting." },
        { metric: "Watch time", value: "0.3 hours", interpretation: "Total estimated watch time.", action: "Grow with stronger packaging and retention." },
        { metric: "Net subscribers", value: "3", interpretation: "Growth in the 28-day period.", action: "Use explicit subscribe cue sparingly." },
        { metric: "Current subscribers", value: "4", interpretation: "Realtime count.", action: "Small base; percentages will be volatile." },
        { metric: "Impressions", value: "4,000", interpretation: "Thumbnail impressions.", action: "Strong opportunity to improve packaging." },
        { metric: "Impression CTR", value: "1.3%", interpretation: "4K impressions produced 54 views.", action: "Test stronger thumbnail/title promise." },
        { metric: "Published videos / Shorts", value: "14 / 9", interpretation: "Long-form vs short uploads.", action: "Prioritise strongest stories." },
        { metric: "Shorts stayed to watch", value: "16.5%", interpretation: "83.5% swiped away.", action: "Lead with the joke, result or emotional promise." },
      ],
      topContent: [
        { rank: 1, title: "Preserving Nani's Secret Baingan Bharta", value: "43 views", extra: "0:22 avg · 59.5% viewed", note: "Top long-form result; meaningful retention." },
        { rank: 2, title: "A New Menu Every Month | The OPR Vision", value: "43 views", extra: "0:08 avg · 75.3% viewed", note: "Strong short completion." },
        { rank: 3, title: "A Menu Written by the People | The OPR Vision", value: "35 views", extra: "0:08 avg · 74.4% viewed", note: "Similar message; slightly less reach." },
        { rank: 4, title: "The OPR Idea | A Menu Written by the People", value: "12 views", extra: "0:08 avg · 74.4% viewed", note: "Packaging/distribution limited." },
        { rank: 5, title: "Other Peoples Recipes, Every Recipe has a Story", value: "8 views", extra: "0:09 avg · 87.8% viewed", note: "High retention on a small sample." },
      ],
      discoverySources: [
        { source: "Shorts feed", share: 0.391, approxViews: 72, meaning: "Largest source.", action: "Improve first-second hook." },
        { source: "Suggested videos", share: 0.261, approxViews: 48, meaning: "YouTube recommendations.", action: "Create connected series/playlists." },
        { source: "Channel pages", share: 0.12, approxViews: 22, meaning: "Visitors browsing OPR.", action: "Improve channel homepage sections." },
        { source: "YouTube search", share: 0.098, approxViews: 18, meaning: "Search discovery.", action: "Use precise recipe titles/descriptions." },
        { source: "Other YouTube features", share: 0.054, approxViews: 10, meaning: "Miscellaneous internal surfaces.", action: "Monitor." },
        { source: "Other", share: 0.076, approxViews: 14, meaning: "Remaining sources.", action: "Monitor." },
      ],
      note: "A 1.3% impression CTR is the clearest YouTube constraint. A working target of 3–5% is a planning goal, not a forecast; judge it alongside average view duration so stronger packaging does not attract the wrong viewer.",
    },
    tiktok: {
      handle: "@opr_uk",
      period: "TikTok Studio · Last 28 days to 17 Aug 2026",
      metrics: [
        { metric: "Video views", value: "4,700", interpretation: "Largest native exposure total among OPR social channels.", action: "Convert discovery into profile/site action." },
        { metric: "Likes", value: "34", interpretation: "Primary visible engagement.", action: "Test stronger emotional/comedic payoffs." },
        { metric: "Comments", value: "1", interpretation: "Very low conversation.", action: "Ask specific, easy-to-answer recipe questions." },
        { metric: "Shares", value: "3", interpretation: "Early sharing signal.", action: "Create family-recognition moments." },
        { metric: "Profile views", value: "18", interpretation: "0.38% of video views reached the profile.", action: "Strengthen on-screen and caption CTA." },
        { metric: "Total followers", value: "3", interpretation: "Current total.", action: "Report per 1K views while small." },
      ],
      topContent: [
        { rank: 1, title: "Dave in the kitchen; Rubble keeping watch", value: "255 views (7d)", extra: "Published 1 week ago", note: "Strongest recent reach." },
        { rank: 2, title: "Dave's Butter Chicken", value: "244 views (7d)", extra: "Published 3 days ago", note: "Direct recipe CTA included." },
        { rank: 3, title: "Recipe of the Month", value: "244 views (7d)", extra: "Published 1 week ago", note: "Participation prompt." },
        { rank: 4, title: "Some recipes are remembered", value: "243 views (7d)", extra: "Published 6 days ago", note: "Story-led message." },
        { rank: 5, title: "Mummy Morris & Rubble: Beef Casserole", value: "242 views (7d)", extra: "Published 4 days ago", note: "Caption contains accidental desktop/UI text after the intended copy—remove or repost immediately." },
      ],
      discoverySources: [
        { source: "For You", share: 0.961, approxViews: 4517, meaning: "Excellent algorithmic discovery.", action: "" },
        { source: "Personal profile", share: 0.034, approxViews: 160, meaning: "Small returning/profile traffic.", action: "" },
        { source: "Search", share: 0.005, approxViews: 24, meaning: "Search contribution is minimal.", action: "" },
      ],
      note: "The public Mummy Morris caption includes appended interface text (for example app tabs and file names). This is a confirmed content-quality issue, not an analytics inference.",
    },
  },

  measurementActions: {
    linkClicks: [
      { linkKey: "founding-table", clicks: 1, firstClick: "17 Aug 10:11", lastClick: "17 Aug 10:11", status: "Legacy key", interpretation: "New label is Join Our Table; update the analytics key when practical." },
      { linkKey: "recipe-of-month", clicks: 1, firstClick: "17 Aug 10:21", lastClick: "17 Aug 10:21", status: "Current", interpretation: "Single launch-day click." },
    ],
    gaps: [
      { gap: "Social source attribution", currentState: "One shared /links URL and link_key only.", risk: "Platform-specific traffic is hidden.", fix: "Use /links?src=instagram etc.", priority: "P1", owner: "Site", due: "7 days" },
      { gap: "Campaign attribution", currentState: "Vercel Hobby has no UTM report.", risk: "Campaigns cannot be compared.", fix: "Retain UTMs in destination URLs and log them first-party.", priority: "P1", owner: "Site", due: "14 days" },
      { gap: "Real-user performance", currentState: "Vercel Speed Insights disabled; GSC has no field CWV.", risk: "Regressions may go unseen.", fix: "Enable Speed Insights.", priority: "P2", owner: "Site", due: "7 days" },
      { gap: "Conversion events", currentState: "Database actions exist; Web Analytics custom events unavailable on Hobby.", risk: "Traffic-to-action path is incomplete.", fix: "Create privacy-safe server-side event summary.", priority: "P2", owner: "Site", due: "30 days" },
      { gap: "Cross-platform comparison", currentState: "Different periods and definitions.", risk: "False totals and conclusions.", fix: "Adopt a fixed month-end reporting window.", priority: "P2", owner: "Analytics", due: "Month-end" },
    ],
    deliveryPlan: [
      { priority: "P1", workstream: "Measurement", action: "Source-code every social bio and campaign link.", baseline: "2 /links clicks; source unknown", goal30d: "All profiles coded", goal90d: "Monthly source-to-site report", owner: "Site/social", timing: "Week 1", status: "Not started" },
      { priority: "P1", workstream: "Authority", action: "Earn relevant independent backlinks.", baseline: "1 linking domain", goal30d: "Outreach list + 3 pitches/week", goal90d: "10+ new relevant domains", owner: "PR/content", timing: "Weekly", status: "Not started" },
      { priority: "P1", workstream: "Indexing", action: "Consolidate community/1 duplicate and validate.", baseline: "3 discovered/not indexed", goal30d: "Redirect/canonical live", goal90d: "Coverage resolved", owner: "Site", timing: "Week 1", status: "Not started" },
      { priority: "P1", workstream: "Video SEO", action: "Publish dedicated watch pages with VideoObject and transcripts.", baseline: "2 indexed videos; 1 excluded", goal30d: "Priority template live", goal90d: "Priority film library eligible", owner: "Site/content", timing: "30–90 days", status: "Not started" },
      { priority: "P1", workstream: "TikTok hygiene", action: "Remove/repost corrupted Beef Casserole caption.", baseline: "Caption contains UI text", goal30d: "Correct today", goal90d: "Pre-publish checklist adopted", owner: "Social", timing: "Today", status: "Not started" },
      { priority: "P2", workstream: "YouTube", action: "Test stronger titles and thumbnails.", baseline: "CTR 1.3%", goal30d: "Two controlled tests", goal90d: "Working CTR 3–5% with retention protected", owner: "Video", timing: "Fortnightly", status: "Not started" },
      { priority: "P2", workstream: "Recipe SEO", action: "Expand verified recipe data and helpful copy.", baseline: "4 valid Recipe items", goal30d: "Bhindi + Jollof refresh", goal90d: "All priority recipes complete", owner: "Content", timing: "Monthly", status: "Not started" },
      { priority: "P2", workstream: "Instagram", action: "Convert profile visits with /links and pinned CTA.", baseline: "174 profile visits; clicks unavailable", goal30d: "Tracking live", goal90d: "Improving profile-to-link rate", owner: "Social", timing: "Week 1", status: "Not started" },
      { priority: "P2", workstream: "Pinterest", action: "Publish search-led vertical recipe Pins.", baseline: "126 impressions; 1 outbound", goal30d: "2 Pins/recipe", goal90d: "Consistent outbound growth", owner: "Social/content", timing: "Weekly", status: "Not started" },
      { priority: "P2", workstream: "Accessibility", action: "Fix contrast and add caption tracks.", baseline: "Lighthouse accessibility 97", goal30d: "Issues fixed", goal90d: "Score 100 maintained", owner: "Site", timing: "30 days", status: "Not started" },
      { priority: "P2", workstream: "Performance", action: "Enable Speed Insights.", baseline: "No field data", goal30d: "Collection active", goal90d: "Monthly CWV baseline", owner: "Site", timing: "Week 1", status: "Not started" },
      { priority: "P3", workstream: "Reporting", action: "Repeat this workbook at month-end.", baseline: "First baseline", goal30d: "August close", goal90d: "Three-month trend", owner: "Analytics", timing: "Monthly", status: "Scheduled" },
    ],
    note: "Only two clicks have been recorded since /links launched on 17 August. These may include implementation QA, so they are not yet evidence of audience behaviour. Do not buy bulk backlinks, fabricate reviews/ratings, or add invented nutrition/timing data.",
  },
};
