const COUNTRY_NAMES: Record<string, string> = {
  are: "United Arab Emirates",
  arg: "Argentina",
  aus: "Australia",
  aut: "Austria",
  bel: "Belgium",
  bra: "Brazil",
  can: "Canada",
  che: "Switzerland",
  chl: "Chile",
  chn: "China",
  col: "Colombia",
  cyp: "Cyprus",
  cze: "Czechia",
  deu: "Germany",
  dnk: "Denmark",
  egy: "Egypt",
  esp: "Spain",
  fin: "Finland",
  fra: "France",
  gbr: "United Kingdom",
  grc: "Greece",
  hkg: "Hong Kong",
  hrv: "Croatia",
  hun: "Hungary",
  idn: "Indonesia",
  ind: "India",
  irl: "Ireland",
  isl: "Iceland",
  isr: "Israel",
  ita: "Italy",
  jpn: "Japan",
  ken: "Kenya",
  kor: "South Korea",
  lka: "Sri Lanka",
  lux: "Luxembourg",
  mar: "Morocco",
  mex: "Mexico",
  mlt: "Malta",
  mys: "Malaysia",
  nga: "Nigeria",
  nld: "Netherlands",
  nor: "Norway",
  nzl: "New Zealand",
  pak: "Pakistan",
  phl: "Philippines",
  pol: "Poland",
  prt: "Portugal",
  rou: "Romania",
  rus: "Russia",
  sau: "Saudi Arabia",
  sgp: "Singapore",
  swe: "Sweden",
  tha: "Thailand",
  tur: "Türkiye",
  ukr: "Ukraine",
  usa: "United States",
  vnm: "Vietnam",
  zaf: "South Africa",
};

const regionNames = new Intl.DisplayNames(["en-GB"], { type: "region" });

export function countryName(value: string): string {
  const code = value.trim().toLowerCase();
  if (/^[a-z]{2}$/.test(code)) {
    return regionNames.of(code.toUpperCase()) ?? value;
  }
  return COUNTRY_NAMES[code] ?? value;
}
