-- Privacy-safe first-party attribution. These records deliberately contain no
-- name, email address, IP address, browser identifier or cross-site identifier.

alter table public.link_clicks
  add column if not exists source text,
  add column if not exists utm_source text,
  add column if not exists utm_medium text,
  add column if not exists utm_campaign text,
  add column if not exists destination text;

update public.link_clicks
set link_key = 'join-our-table'
where link_key = 'founding-table';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'link_clicks_source_check') then
    alter table public.link_clicks add constraint link_clicks_source_check
      check (source is null or source in ('instagram', 'tiktok', 'facebook', 'youtube', 'pinterest'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'link_clicks_utm_source_check') then
    alter table public.link_clicks add constraint link_clicks_utm_source_check
      check (utm_source is null or utm_source in ('instagram', 'tiktok', 'facebook', 'youtube', 'pinterest'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'link_clicks_utm_medium_check') then
    alter table public.link_clicks add constraint link_clicks_utm_medium_check
      check (utm_medium is null or utm_medium = 'social');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'link_clicks_utm_campaign_check') then
    alter table public.link_clicks add constraint link_clicks_utm_campaign_check
      check (utm_campaign is null or utm_campaign ~ '^[a-z0-9][a-z0-9_-]{0,63}$');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'link_clicks_destination_length_check') then
    alter table public.link_clicks add constraint link_clicks_destination_length_check
      check (destination is null or char_length(destination) <= 200);
  end if;
end
$$;

create index if not exists link_clicks_source_created_at_idx
  on public.link_clicks (source, created_at desc);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_key text not null check (event_key in (
    'home_cookbook',
    'cookbook_share',
    'film_recipe',
    'founder_join',
    'join_table_success',
    'recipe_submission_success'
  )),
  page_path text not null check (char_length(page_path) between 1 and 200),
  destination text null check (destination is null or char_length(destination) <= 200),
  source text null check (source is null or source in ('instagram', 'tiktok', 'facebook', 'youtube', 'pinterest')),
  utm_source text null check (utm_source is null or utm_source in ('instagram', 'tiktok', 'facebook', 'youtube', 'pinterest')),
  utm_medium text null check (utm_medium is null or utm_medium = 'social'),
  utm_campaign text null check (utm_campaign is null or utm_campaign ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
  created_at timestamptz not null default now()
);

create index if not exists site_events_source_created_at_idx
  on public.site_events (source, created_at desc);

create index if not exists site_events_key_created_at_idx
  on public.site_events (event_key, created_at desc);

alter table public.site_events enable row level security;
alter table public.site_events force row level security;
revoke all on public.site_events from anon, authenticated;

comment on table public.site_events is
  'Privacy-safe OPR CTA and conversion counts. Contains no PII or visitor identifier.';
