-- Part 2 of the secure submission pipeline: no rate limiting exists anywhere
-- in the app today, so the public write routes are effectively open. This
-- table backs a simple per-IP/per-route counter checked from the service-role
-- client each route already uses — no external service required.
create table if not exists public.api_rate_limits (
  id bigint generated by default as identity primary key,
  route text not null,
  client_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists api_rate_limits_lookup_idx
  on public.api_rate_limits (route, client_key, created_at desc);

-- Old rows are just noise once their window has passed; nothing reads past 24h.
create index if not exists api_rate_limits_created_at_idx
  on public.api_rate_limits (created_at);

alter table public.api_rate_limits enable row level security;
alter table public.api_rate_limits force row level security;

-- Service-role only: no anon/authenticated grants, no policies.
revoke all on public.api_rate_limits from anon, authenticated;

comment on table public.api_rate_limits is
  'Per-IP/per-route submission counters for rate limiting. Service-role access only.';
