-- Basic click counter for the /links (link-in-bio) page. Anonymous, no PII —
-- just which link was tapped and when, so it's not worth the weight of a
-- separate analytics service.
create table if not exists public.link_clicks (
  id bigint generated by default as identity primary key,
  link_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists link_clicks_link_key_idx
  on public.link_clicks (link_key, created_at desc);

alter table public.link_clicks enable row level security;
alter table public.link_clicks force row level security;

-- Service-role only: no anon/authenticated grants, no policies. The public
-- /api/links/click route validates the key and inserts via the service-role
-- client rather than allowing anon writes directly.
revoke all on public.link_clicks from anon, authenticated;

comment on table public.link_clicks is
  'Click counts for the /links landing page. Service-role access only.';
