create table if not exists public.analytics_daily_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  captured_at timestamptz not null default now(),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists analytics_daily_snapshots_captured_at_idx
  on public.analytics_daily_snapshots (captured_at desc);

alter table public.analytics_daily_snapshots enable row level security;
alter table public.analytics_daily_snapshots force row level security;

revoke all on public.analytics_daily_snapshots from anon, authenticated;

comment on table public.analytics_daily_snapshots is
  'Daily service-role-only copies of the OPR management analytics baseline.';
create table if not exists public.analytics_daily_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  captured_at timestamptz not null default now(),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists analytics_daily_snapshots_captured_at_idx
  on public.analytics_daily_snapshots (captured_at desc);

alter table public.analytics_daily_snapshots enable row level security;
alter table public.analytics_daily_snapshots force row level security;

revoke all on public.analytics_daily_snapshots from anon, authenticated;

comment on table public.analytics_daily_snapshots is
  'Daily service-role-only copies of the OPR management analytics baseline.';
