-- People who want to watch Dave cook live over Zoom. Service-role only,
-- same lockdown as founding_table_members: no public policies, so only
-- the admin client (and thus our API route) can read or write rows.
create table if not exists public.cookalong_signups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(trim(name)) between 1 and 120),
  email text not null unique check (email = lower(email)),
  marketing_opt_in boolean not null default false,
  marketing_unsubscribed_at timestamptz null,
  source text not null default 'website'
);

create index if not exists cookalong_signups_marketing_opt_in_idx
  on public.cookalong_signups (marketing_opt_in)
  where marketing_opt_in = true;

alter table public.cookalong_signups enable row level security;

comment on table public.cookalong_signups is
  'Signups for Dave''s live Zoom cook-along events; every signup gets the event recipe list and join link regardless of marketing_opt_in.';
