-- People who have made a published OPR recipe can share a photo and a note.
-- Nothing appears publicly until an OPR administrator approves it.
create table if not exists public.recipe_community_cooks (
  id bigint generated by default as identity primary key,
  recipe_submission_id bigint not null references public.recipe_submissions(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  note text null check (char_length(note) <= 1000),
  photo_path text null,
  is_approved boolean not null default false,
  created_at timestamptz not null default now(),
  approved_at timestamptz null
);

create index if not exists recipe_community_cooks_recipe_idx
  on public.recipe_community_cooks (recipe_submission_id, is_approved, created_at desc);

alter table public.recipe_community_cooks enable row level security;

-- The public can only read contributions which OPR has approved.
drop policy if exists "Approved community cooks are public" on public.recipe_community_cooks;
create policy "Approved community cooks are public"
  on public.recipe_community_cooks
  for select
  to anon, authenticated
  using (is_approved = true);

comment on table public.recipe_community_cooks is
  'Community photos and notes about making an OPR recipe; reviewed by OPR before publication.';
